TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------

#  Optimization of db files using dbst (DEFAULT: NO)
#DB_OPT = YES

DB += mcor.template

include $(TOP)/configure/RULES

